table DimCustomer
	lineageTag: e02fd75e-e723-43cc-be9b-9aba7d3bbe88

	column CustomerID
		dataType: string
		lineageTag: 09118763-f53f-4de7-90f8-5d0b6202c921
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column customer_unique_id
		dataType: string
		lineageTag: f039b9ef-3982-44cc-a54b-0bbbbd117006
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: 39709229-874c-4335-9c71-73f72a87081e
		summarizeBy: none
		sourceColumn: customer_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 0539aebb-c861-4677-bf47-4d205d11ff51
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 3f600597-d4e8-400e-82ad-8c6d3670560b
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Path\To\RetailPulse-Sales-Intelligence\data\olist_customers_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", type text}, {"customer_unique_id", type text}, {"customer_zip_code_prefix", Int64.Type}, {"customer_city", type text}, {"customer_state", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"customer_city", "City"}, {"customer_state", "State"}, {"customer_id", "CustomerID"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

