table olist_order_reviews_dataset
	lineageTag: 080e8b3d-f1eb-4faf-8120-993e1f545202

	column review_id
		dataType: string
		lineageTag: 05bd7407-1551-41d5-9024-c3566890a4ac
		summarizeBy: none
		sourceColumn: review_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: eebb4d39-dcbf-4a0a-8a48-aba1aa3a4078
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: bc822e90-16b7-4de4-b272-754f3ea67479
		summarizeBy: sum
		sourceColumn: review_score

		annotation SummarizationSetBy = Automatic

	column review_comment_title
		dataType: string
		lineageTag: 3c7716d2-910d-4387-8adf-5e4e45ff19b7
		summarizeBy: none
		sourceColumn: review_comment_title

		annotation SummarizationSetBy = Automatic

	column review_comment_message
		dataType: string
		lineageTag: 274c3df8-8a3e-4f78-b057-4390ecc5a0d4
		summarizeBy: none
		sourceColumn: review_comment_message

		annotation SummarizationSetBy = Automatic

	column review_creation_date
		dataType: dateTime
		formatString: General Date
		lineageTag: bf8ebb5f-adf5-4e9d-9c90-8a4ac7518f9e
		summarizeBy: none
		sourceColumn: review_creation_date

		variation Variation
			isDefault
			relationship: 211e0234-40a9-4b35-97ee-e1a744360cbb
			defaultHierarchy: LocalDateTable_595201e8-296b-428f-aaa8-5ce350ff0896.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column review_answer_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 71f181a6-e942-43ff-a295-a0a364dcbf7f
		summarizeBy: none
		sourceColumn: review_answer_timestamp

		variation Variation
			isDefault
			relationship: 37d69537-b775-465e-b72d-2ed5f51944d5
			defaultHierarchy: LocalDateTable_71e03977-ca79-4aa2-879e-5ce2d5b5192c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition olist_order_reviews_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\FADOU\Desktop\RetailPulse-AI-Sales-Intelligence\data\olist_order_reviews_dataset.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"review_id", type text}, {"order_id", type text}, {"review_score", Int64.Type}, {"review_comment_title", type text}, {"review_comment_message", type text}, {"review_creation_date", type datetime}, {"review_answer_timestamp", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

